import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { resolve } from "styled-jsx/css";
import loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link className="link" href="/">
          Acceuil
        </Link>
        <Link className="link" href="/about">
          Apropos
        </Link>
      </div>
      <div>
        <h1>Accueil</h1>
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
        dfsdf sfsfsd sfsdf sfsdfs fsdfsfsdfs fsfsdfsdfsd fsdfsdfsdfsdf sdfsdfsdf sdfsddfsdf sdff
      </div>
    </>
  );
}

export async function getServerSideProps() {
  await loading()

  return {
    props: {},
  };
}
